### ISSUE TITLE
Error ExceptionInInitializerError in Jenkins 2.462.2

### ISSUE THREAD

**Issue by jordibellido** [jenkinsci/aws-secrets-manager-secret-source-plugin#188]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.462.2
OS: Linux - 4.15.0-213-generic
Java: 17.0.12 - Amazon.com Inc. (OpenJDK 64-Bit Server VM)
---
JDK_Parameter_Plugin:1.2
Office-365-Connector:4.21.5
all-changes:1.5
allure-jenkins-plugin:2.31.1
analysis-model-api:12.7.0
ansible:403.v8d0ca_dcb_b_502
ansicolor:1.0.4
ant:511.v0a_a_1a_334f41b_
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.4-118.v199115451c4d
artifactory:4.0.8
asm-api:9.7-33.v4d23ef79fcc8
atlassian-bitbucket-server-integration:4.0.0
authentication-tokens:1.119.v50285141b_7e1
aws-credentials:231.v08a_59f17d742
aws-java-sdk:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-api-gateway:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-autoscaling:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-cloudformation:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-cloudfront:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-codebuild:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-codedeploy:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-ec2:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-ecr:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-ecs:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-efs:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-elasticbeanstalk:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-elasticloadbalancingv2:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-iam:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-kinesis:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-lambda:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-logs:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-minimal:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-organizations:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-secretsmanager:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-sns:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-sqs:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-ssm:1.12.767-467.vb_e93f0c614b_6
aws-secrets-manager-credentials-provider:1.214.va_0a_d8268d068
badge:2.1
basic-branch-build-strategies:81.v05e333931c7d
bitbucket-push-and-pull-request:3.1.1
bootstrap4-api:4.6.0-6
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.78.1-248.ve27176eb_46cb_
branch-api:2.1178.v969d9eb_c728e
build-blocker-plugin:166.vc82fc20b_a_ed6
build-failure-analyzer:2.5.2
build-name-setter:2.4.3
build-timestamp:1.0.3
build-token-root:151.va_e52fe3215fc
build-user-vars-plugin:176.vb_9c7907fd524
buildtriggerbadge:251.vdf6ef853f3f5
built-on-column:1.4
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.2.1
claim:554.va_f9b_58b_0a_088
cloudbees-bitbucket-branch-source:888.v8e6d479a_1730
cloudbees-folder:6.951.v5f91d88d76b_b_
cobertura:1.17
code-coverage-api:4.99.0
command-launcher:115.vd8b_301cc15d0
commons-compress-api:1.26.1-2
commons-httpclient3-api:3.1-3
commons-lang3-api:3.17.0-84.vb_b_938040b_078
commons-text-api:1.12.0-129.v99a_50df237f7
conditional-buildstep:1.4.3
config-file-provider:978.v8e85886ffdc4
configuration-as-code:1850.va_a_8c31d3158b_
configurationslicing:548.ve92d48e66b_f8
copyartifact:749.vfb_dca_a_9b_6549
coverage:1.16.1
credentials:1378.v81ef4269d764
credentials-binding:681.vf91669a_32e45
cucumber-reports:5.8.3
cucumber-testresult-plugin:0.10.1
cucumber-trends-report:1.3
dark-theme:479.v661b_1b_911c01
dashboard-view:2.517.v776a_b_811a_b_4e
data-tables-api:2.1.6-1
description-setter:239.vd0a_6b_785f92d
display-url-api:2.204.vf6fddd8a_8b_e9
docker-build-publish:1.4.0
docker-commons:443.v921729d5611d
docker-java-api:3.3.6-90.ve7c5c7535ddd
docker-workflow:580.vc0c340686b_54
durable-task:577.v2a_8a_4b_7c0247
ec2:1688.v8c07e01d657f
echarts-api:5.5.1-1
eddsa-api:0.3.0-4.v84c6f0f4969e
email-ext:1814.v404722f34263
embeddable-build-status:487.va_0ef04c898a_2
envinject:2.919.v009a_a_1067cd0
envinject-api:1.199.v3ce31253ed13
extended-choice-parameter:382.v5697b_32134e8
extended-read-permission:53.v6499940139e5
external-monitor-job:215.v2e88e894db_f8
favorite:2.221.v19ca_666b_62f5
flatpickr-api:4.6.13-5.v534d8025a_a_59
flexible-publish:0.16.1
font-awesome-api:6.6.0-2
forensics-api:2.6.0
generic-webhook-trigger:2.2.2
git:5.5.1
git-client:5.0.0
git-forensics:2.2.1
git-parameter:0.9.19
git-server:126.v0d945d8d2b_39
github:1.40.0
github-api:1.321-468.v6a_9f5f2d5a_7e
github-branch-source:1797.v86fdb_4d57d43
global-build-stats:307.v03dce5a_f8943
gradle:2.13
groovy:457.v99900cb_85593
groovy-postbuild:228.vcdb_cf7265066
gson-api:2.11.0-41.v019fcf6125dc
handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
htmlpublisher:1.36
http_request:1.19
instance-identity:185.v303dc7c645f9
ionicons-api:74.v93d5eb_813d5f
ivy:2.6
jackson2-api:2.17.0-379.v02de8ec9f64c
jacoco:3.3.6
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javadoc:280.v050b_5c849f69
javax-activation-api:1.2.0-7
javax-mail-api:1.6.2-10
jaxb:2.3.9-1
jdk-tool:80.v8a_dee33ed6f0
jenkins-design-language:1.27.16
jersey2-api:2.44-151.v6df377fff741
jfrog:1.5.3
jira:3.13
jjwt-api:0.11.5-112.ve82dfb_224b_a_d
jnr-posix-api:3.1.19-2
job-dsl:1.89
jobConfigHistory:1268.v75ce751da_911
joda-time-api:2.13.0-85.vb_64d1c2921f1
jquery:1.12.4-1
jquery3-api:3.7.1-2
jsch:0.2.16-86.v42e010d9484b_
json-api:20240303-41.v94e11e6de726
json-path-api:2.9.0-58.v62e3e85b_a_655
junit:1300.v03d9d8a_cf1fb_
kubernetes-cli:1.12.1
kubernetes-client-api:6.10.0-240.v57880ce8b_0b_2
kubernetes-credentials:190.v03c305394deb_
ldap:725.v3cb_b_711b_1a_ef
lockable-resources:1310.v99ca_947ed698
log-parser:2.3.5
m2release:0.16.4
mailer:472.vf7c289a_4b_420
mapdb-api:1.0.9-40.v58107308b_7a_7
mask-passwords:173.v6a_077a_291eb_5
matrix-auth:3.2.2
matrix-project:832.va_66e270d2946
maven-plugin:3.23
mercurial:1260.vdfb_723cdcc81
metrics:4.2.21-451.vd51df8df52ec
mina-sshd-api-common:2.13.2-125.v200281b_61d59
mina-sshd-api-core:2.13.2-125.v200281b_61d59
monitoring:1.99.0
msbuild:1.34
multibranch-scan-webhook-trigger:1.0.11
next-executions:327.v136ff959e97b_
node-iterator-api:55.v3b_77d4032326
nodejs:1.6.2
nodelabelparameter:1.12.0
okhttp-api:4.11.0-172.vda_da_1feeb_c6e
openshift-client:1.1.0.424.v829cb_ccf8798
pam-auth:1.11
parameterized-scheduler:277.v61a_4b_a_49a_c5c
parameterized-trigger:806.vf6fff3e28c3e
performance:962.v95a_4913d332e
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-github-lib:61.v629f2cc41d83
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:730.ve57b_34648c63
pipeline-input-step:495.ve9c153f6067b_
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2214.vb_b_34b_2ea_9b_83
pipeline-model-definition:2.2214.vb_b_34b_2ea_9b_83
pipeline-model-extensions:2.2214.vb_b_34b_2ea_9b_83
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2214.vb_b_34b_2ea_9b_83
pipeline-stage-view:2.34
pipeline-utility-steps:2.17.0
plain-credentials:183.va_de8f1dd5a_2b_
plugin-usage-plugin:4.5
plugin-util-api:5.1.0
popper-api:1.16.1-3
popper2-api:2.11.6-5
postbuildscript:3.3.0-654.v67cf36130d78
prism-api:1.29.0-17
pubsub-light:1.18
rebuild:332.va_1ee476d8f6d
release:2.19
remote-file:1.24
resource-disposer:0.23
role-strategy:743.v142ea_b_d5f1d3
run-condition:1.7
rundeck:3.6.13
s3:483.vcb_db_3dcee68f
saferestart:0.7
saml:4.464.vea_cb_75d7f5e0
sauce-ondemand:1.214
scm-api:696.v778d637b_a_762
script-security:1362.v67dc1f0e1b_b_3
scriptler:363.vd97ef616cb_f9
sidebar-link:2.4.1
snakeyaml-api:2.3-123.v13484c65210a_
sonar:2.17.2
sse-gateway:1.27
ssh:2.6.1
ssh-agent:376.v8933585c69d3
ssh-credentials:343.v884f71d78167
ssh-slaves:2.973.v0fa_8c0dea_f9f
ssh-steps:2.0.68.va_d21a_12a_6476
sshd:3.330.vc866a_8389b_58
stash-pullrequest-builder:1.17
stashNotifier:1.507.vb_7300a_1a_a_d10
strict-crumb-issuer:2.1.1
structs:338.v848422169819
swarm:3.47
terraform:1.0.10
testng-plugin:835.v51ed3da_fcc35
theme-manager:262.vc57ee4a_eda_5d
timestamper:1.27
tm4j-automation:3.3.4
token-macro:400.v35420b_922dcb_
trilead-api:2.147.vb_73cc728a_32e
uno-choice:2.8.3
variant:60.v7290fc0eb_b_cd
veracode-scan:24.2.23.0
versionnumber:1.11
view-job-filters:382.vdf2d5e3f02f0
warnings-ng:11.9.0
workflow-aggregator:600.vb_57cdd26fdd7
workflow-api:1336.vee415d95c521
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3964.v0767b_4b_a_0b_fa_
workflow-cps-global-lib:612.v55f2f80781ef
workflow-durable-task-step:1371.vb_7cec8f3b_95e
workflow-job:1436.vfa_244484591f
workflow-multibranch:795.ve0cb_1f45ca_9a_
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:678.v3ee58b_469476
workflow-support:926.v9f4f9b_b_98c19
ws-cleanup:0.46
xlrelease-plugin:22.0.1
xvfb:1.2
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Amazon Linux 2023.5.20240903

### Reproduction steps

1. Have a running installation of Jenkins 2.462.2.
2. Go to "Manage Jenkins -> Plugins".
3. Install the plugin [AWS Secrets Manager SecretSource](https://plugins.jenkins.io/aws-secrets-manager-secret-source).
4. Restart the Jenkins service.

### Expected Results

1. The plugin is installed successfully.
2. The Jenkins service is restarted with no errors:
```
Sep 25, 2024 7:50:28 AM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Sep 25, 2024 7:50:29 AM jenkins.InitReactorRunner$1 onAttained
INFO: System config loaded
Sep 25, 2024 7:50:29 AM jenkins.InitReactorRunner$1 onAttained
INFO: System config adapted
Sep 25, 2024 7:50:29 AM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
Sep 25, 2024 7:50:29 AM org.jenkins.plugins.lockableresources.NodesMirror createNodeResources
INFO: lockable-resources-plugin: configure node resources
Sep 25, 2024 7:50:29 AM jenkins.InitReactorRunner$1 onAttained
INFO: Configuration for all jobs updated
Sep 25, 2024 7:50:29 AM jenkins.InitReactorRunner$1 onAttained
INFO: Completed initialization
Sep 25, 2024 7:50:29 AM org.jenkinsci.plugins.gwt.jobfinder.JobFinderImpersonater$JobItemListener onLoaded
INFO: Loaded 0 jobs in cache
Sep 25, 2024 7:50:29 AM hudson.lifecycle.Lifecycle onReady
INFO: Jenkins is fully up and running
```

### Actual Results

1. The plugin is installed successfully.
2. The Jenkins service is restarted and shows the below error:
```
Sep 25, 2024 7:46:49 AM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Sep 25, 2024 7:46:52 AM jenkins.InitReactorRunner$1 onAttained
INFO: System config loaded
Sep 25, 2024 7:46:53 AM com.amazonaws.util.VersionInfoUtils printDeprecationAnnouncement
WARNING: The AWS SDK for Java 1.x entered maintenance mode starting July 31, 2024 and will reach end of support on December 31, 2025. For more information, see https://aws.amazon.com/blogs/developer/the-aws-sdk-for-java-1-x-is-in-maintenance-mode-effective-july-31-2024/
You can print where on the file system the AWS SDK for Java 1.x core runtime is located by setting the AWS_JAVA_V1_PRINT_LOCATION environment variable or aws.java.v1.printLocation system property to 'true'.
This message can be disabled by setting the AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT environment variable or aws.java.v1.disableDeprecationAnnouncement system property to 'true'.
The AWS SDK for Java 1.x is being used here:
at java.base/java.lang.Thread.getStackTrace(Thread.java:1619)
at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.util.VersionInfoUtils.printDeprecationAnnouncement(VersionInfoUtils.java:81)
at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.util.VersionInfoUtils.<clinit>(VersionInfoUtils.java:59)
at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:94)
at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.ClientConfigurationFactory.getDefaultConfig(ClientConfigurationFactory.java:46)
at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.ClientConfigurationFactory.getConfig(ClientConfigurationFactory.java:36)
at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.client.builder.AwsClientBuilder.resolveClientConfiguration(AwsClientBuilder.java:169)
at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.client.builder.AwsClientBuilder.access$000(AwsClientBuilder.java:54)
at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.client.builder.AwsClientBuilder$SyncBuilderParams.<init>(AwsClientBuilder.java:505)
at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.client.builder.AwsClientBuilder.getSyncClientParams(AwsClientBuilder.java:441)
at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
at PluginClassLoader for aws-secrets-manager-secret-source//io.jenkins.plugins.casc.secretsmanager.AwsSecretsManagerSecretSource.createClient(AwsSecretsManagerSecretSource.java:74)
at PluginClassLoader for aws-secrets-manager-secret-source//io.jenkins.plugins.casc.secretsmanager.AwsSecretsManagerSecretSource.init(AwsSecretsManagerSecretSource.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at PluginClassLoader for configuration-as-code//io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:815)
at PluginClassLoader for configuration-as-code//io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:699)
at PluginClassLoader for configuration-as-code//io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:356)
at PluginClassLoader for configuration-as-code//io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:345)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:109)
at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:185)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
at jenkins.model.Jenkins$5.runTask(Jenkins.java:1175)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
Sep 25, 2024 7:46:54 AM jenkins.model.Jenkins$5 runTask
WARNING: ConfigurationAsCode.init failed perhaps due to plugin dependency issues
java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:115)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:185)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1175)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:109)
	... 9 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.commons.logging.impl.Slf4jLogFactory
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:419)
	at org.apache.commons.logging.LogFactory.lambda$newFactory$3(LogFactory.java:1432)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at org.apache.commons.logging.LogFactory.newFactory(LogFactory.java:1431)
	at org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:934)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:987)
	at org.apache.http.conn.ssl.AbstractVerifier.<init>(AbstractVerifier.java:61)
	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<init>(AllowAllHostnameVerifier.java:44)
	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<clinit>(AllowAllHostnameVerifier.java:46)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
	at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheConnectionManagerFactory.java:90)
	at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:67)
	at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:60)
	at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:50)
	at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:38)
	at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:347)
	at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:331)
	at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:239)
	at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:225)
	at PluginClassLoader for aws-java-sdk-secretsmanager//com.amazonaws.services.secretsmanager.AWSSecretsManagerClient.<init>(AWSSecretsManagerClient.java:189)
	at PluginClassLoader for aws-java-sdk-secretsmanager//com.amazonaws.services.secretsmanager.AWSSecretsManagerClient.<init>(AWSSecretsManagerClient.java:175)
	at PluginClassLoader for aws-java-sdk-secretsmanager//com.amazonaws.services.secretsmanager.AWSSecretsManagerClientBuilder.build(AWSSecretsManagerClientBuilder.java:61)
	at PluginClassLoader for aws-java-sdk-secretsmanager//com.amazonaws.services.secretsmanager.AWSSecretsManagerClientBuilder.build(AWSSecretsManagerClientBuilder.java:27)
	at PluginClassLoader for aws-java-sdk-minimal//com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at PluginClassLoader for aws-secrets-manager-secret-source//io.jenkins.plugins.casc.secretsmanager.AwsSecretsManagerSecretSource.createClient(AwsSecretsManagerSecretSource.java:74)
	at PluginClassLoader for aws-secrets-manager-secret-source//io.jenkins.plugins.casc.secretsmanager.AwsSecretsManagerSecretSource.init(AwsSecretsManagerSecretSource.java:52)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at PluginClassLoader for configuration-as-code//io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:815)
	at PluginClassLoader for configuration-as-code//io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:699)
	at PluginClassLoader for configuration-as-code//io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:356)
	at PluginClassLoader for configuration-as-code//io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:345)
	... 14 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: org/slf4j/MarkerFactory [in thread "ConfigurationAsCode.init"]
	at org.apache.commons.logging.impl.Slf4jLogFactory.<clinit>(Slf4jLogFactory.java:255)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:327)
	... 44 more

Sep 25, 2024 7:46:54 AM jenkins.InitReactorRunner$1 onAttained
INFO: System config adapted
Sep 25, 2024 7:46:54 AM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
Sep 25, 2024 7:46:54 AM org.jenkins.plugins.lockableresources.NodesMirror createNodeResources
INFO: lockable-resources-plugin: configure node resources
Sep 25, 2024 7:46:54 AM jenkins.InitReactorRunner$1 onAttained
INFO: Configuration for all jobs updated
Sep 25, 2024 7:46:54 AM jenkins.InitReactorRunner$1 onAttained
INFO: Completed initialization
Sep 25, 2024 7:46:55 AM hudson.model.DownloadService$Downloadable updateNow
WARNING: No tool installer metadata found for jenkins.plugins.nodejs.tools.MirrorNodeJSInstaller
Sep 25, 2024 7:46:56 AM org.jenkinsci.plugins.gwt.jobfinder.JobFinderImpersonater$JobItemListener onLoaded
INFO: Loaded 0 jobs in cache
Sep 25, 2024 7:46:56 AM hudson.lifecycle.Lifecycle onReady
INFO: Jenkins is fully up and running
```

### Anything else?

This error was not present in Jenkins 2.387.2. It was working fine in 2.440.2, too.

If I uninstall the plugin, the error disappears. If I install it again, the error is back. I have consistently reproduced this issue by installing/uninstalling this plugin.

**Comment by chriskilding** [comment]
This should now (finally) be addressed by the upgrade to AWS Java SDK v2 in #202, which is available in v2 of this plugin.

Feel free to re-open the issue if it still happens.
